config/routes.rb
Rails.application.routes.draw do
  resources :weight_classes
  resources :fighters
  resources :matches do
    member do
      get 'fight'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "fighters#index"
end

app/models/fighter.rb
class Fighter < ApplicationRecord
  has_many :matches_as_fighter_1, class_name: 'Match', foreign_key: 'fighter_1_id'
  has_many :matches_as_fighter_2, class_name: 'Match', foreign_key: 'fighter_2_id'
  has_many :won_matches, class_name: 'Match', foreign_key: 'winner_id'
  has_many :titles
  belongs_to :weight_class
  has_many :weight_classes, through: :weight_class_ranks
  has_many :weight_class_ranks
  has_many :ledgers

  attribute :training_points, default: -> { 0 }
  attribute :level_points, default: -> { 0 }
  attribute :name, default: -> { random_name }
  attribute :nickname, default: -> { random_nickname }
  attribute :birthplace, default: -> { random_birthplace }
  attribute :punch, default: -> { roll_ability }
  attribute :strength, default: -> { roll_ability }
  attribute :speed, default: -> { roll_ability }
  attribute :dexterity, default: -> { roll_ability }
  attribute :weight, default: -> { roll_weight }
  attribute :base_endurance, default: -> { roll_base_endurance }

  after_initialize :set_endurance
  after_initialize :set_weight_class
  before_create :set_endurance_round
  after_create :set_rankings

  def self.random_name
    Faker::Name.male_first_name + ' ' + Faker::Name.last_name
  end

  def self.random_birthplace
    Faker::Address.city
  end

  def self.random_nickname
    Faker::Superhero.name
  end

  def set_rankings
    self.weight_class.update_fighter_ranks
  end

  def set_endurance
    self.endurance ||= self.base_endurance
  end

  def set_endurance_round
    recovery_round =
      case self.base_endurance
      when 0..25
        rand(1..4)
      when 26..50
        rand (1..6)
      when 51..75
        rand(1..8)
      when 76..100
        rand(1..10)
      when 101..170
        rand(1..12)
      when 171..200
        rand(1..12) + 3
      when 201.300
        rand(1..10) + 5
      when 301..400
        rand(1..8) + 7
      when 401..500
        rand(1..6) + 9
      when 501..600
        rand(1..4) + 11
      else
        15
      end
    if !self.endurance_round.nil?
      self.endurance_round = [recovery_round, self.endurance_round].max
    else
      self.endurance_round = recovery_round
    end
  end

  def round_recovery(round)
    return if round > self.endurance_round
    recovery =
      case self.base_endurance
      when 51..75
        rand(1..4)
      when 76..100
        rand(1..6)
      when 101.170
        rand(1..8)
      when 171..200
        rand(1..10)
      when 201.300
        rand(1..12)
      when 301..400
        rand(1..12) + 1
      when 401..500
        rand(1..12) + 2
      when 501..600
        rand(1..12) + 3
      else
        0
      end
    self.endurance = [self.endurance + recovery, self.base_endurance].min
    self.save!
  end

  def buy_training_points
    return false if self.balance < self.training_point_cost(future: true)

    self.training_points += 1
    self.ledgers.create!(description: "Purchased training point", amount: -self.training_point_cost, transaction_date: Date.today)
    self.save!
    true
  end

  def training_point_cost(future: false)
    points = future ? self.training_points + 1 : self.training_points
    cost =
      case points
      when 0..5
        50000
      when 6..10
        500000
      when 11..15
        1000000
      when 16..25
        10000000
      when 25..30
        50000000
      else
        500000000000000000
      end
  end

  def self.needs_training
    fighters = Fighter.includes(:ledgers)
    fighters.select do |fighter|
      balance = fighter.ledgers.sum(:amount)
      balance >= fighter.training_point_cost(future: true)
    end
  end

  def set_weight_class
    self.weight_class ||= WeightClass.find_highest_class_for_weight(self.weight)
  end

  def reset_endurance
    self.endurance = self.base_endurance
  end

  def train
    if (rand(1..100) + self.training_points) >= 90
      self.level_points += 1
      save!
    end
  end

  def self.roll_weight
    if rand() <= 0.99 # 99% chance
      rand(90..225)
    else
      # 1% chance
      rand(226..350)
    end
  end

  def self.roll_ability
    dice = Array.new(4) { rand(1..6) } # Roll four dice and store their results
    ability_score = dice.sort.last(3).sum
    ability_score
  end

  def self.roll_base_endurance
    rand(10..100)
  end

  def wins
    won_matches.count
  end

  def total_matches
    matches_as_fighter_1.count + matches_as_fighter_2.count
  end

  def losses
    # Count matches where the fighter participated but did not win
    # and the match is completed and not a draw
    Match.where("(fighter_1_id = ? OR fighter_2_id = ?) AND winner_id != ? AND winner_id IS NOT NULL AND status_id = 1", self.id, self.id, self.id).count
  end

  def draws
    # Count matches where the fighter participated, match is completed, and there's no winner
    Match.where("(fighter_1_id = ? OR fighter_2_id = ?) AND winner_id IS NULL AND status_id = 1", self.id, self.id).count
  end


  def win_or_loss_streak
    streak = 0
    last_result = nil
    matches = matches_as_fighter_1.where(status_id: 1)
                                  .or(matches_as_fighter_2.where(status_id: 1))
                                  .order(created_at: :desc)

    matches.each do |match|
      current_result = if match.winner_id == self.id
                         'W'
                       else
                         'L'
                       end

      if last_result.nil?
        last_result = current_result
        streak = 1
      elsif last_result == current_result
        streak += 1
      else
        break
      end
    end

    "#{last_result}#{streak}"
  end

  def knockouts
    won_matches.where(result_id: Match.result_ids['ko']).count
  end

  def winning_percentage
    total_matches = wins + losses + draws

    # Guard clause to prevent division by zero
    return 0.0 if total_matches == 0

    (wins.to_f / total_matches).round(3)
  end

  def completed_matches
    (matches_as_fighter_1.or(matches_as_fighter_2)).where(status_id: :completed).order('matches.created_at ASC')
  end

  def pending_matches
    (matches_as_fighter_1.or(matches_as_fighter_2)).where(status_id: :pending)
  end

  def titles_list
    titles.map(&:name).join(', ')
  end

  def current_titles_list
    current_titles.map(&:name).join(', ')
  end

  def increase_endurance
    self.base_endurance += rand(1..20)
    self.endurance = self.base_endurance
    set_endurance_round
  end
  def abbreviated_curent_titles_list
    current_titles.map { |title| title.name.split.map(&:first).join }.join(', ')
  end

  def current_titles
    titles.where(lost_at: nil)
  end

  def current_champion?
    current_titles.exists?
  end

  def total_winnings
    self.ledgers.where("amount > 0").sum(:amount)
  end

  def balance
    ledgers.sum(:amount) || 0
  end

  def past_champion?
    titles.where.not(lost_at: nil).exists?
  end

  def rank
    self.weight_class.weight_class_ranks.find_by(fighter_id: self.id)&.rank_number
  end

  def suggested_opponents
    fighters_in_weight_class = Fighter.where(weight_class_id: self.weight_class_id)
    potential_opponents = fighters_in_weight_class.where.not(id: self.id)

    # Exclude fighters with whom the current fighter has had matches
    potential_opponents = potential_opponents.where.not(id: self.matches_as_fighter_1.pluck(:fighter_2_id) + self.matches_as_fighter_2.pluck(:fighter_1_id))

    # Exclude fighters who are already in pending scheduled matches

    pending_match_fighter_ids = Match.where(weight_class_id: self.weight_class_id, status_id: 0).pluck(:fighter_1_id, :fighter_2_id).flatten.uniq
    potential_opponents = potential_opponents.where.not(id: pending_match_fighter_ids)

    # Calculate the rank difference for each fighter and order by it
    potential_opponents = potential_opponents.sort_by do |fighter|
      (fighter.rank - self.rank).abs
    end

    potential_opponents
  end

  def update_endurance
    additional_endurance = Fighter.roll_base_endurance
    new_endurance = self.endurance + additional_endurance
    if new_endurance > self.base_endurance
      self.endurance = self.base_endurance
    else
      self.endurance = new_endurance
    end
    self.save!
  end

  def self.reset_endurance
    Fighter.all.each do |fighter|
      fighter.reset_endurance
      fighter.save
    end
  end

  def power_score
    scores = {
      punch: score(punch, [[3,6], [7,10], [11,14], [15,17], [18,20], [21, 35]], 10),
      strength: score(strength, [[3,6], [7,10], [11,14], [15,17], [18,20], [21, 35]], 5),
      # base_endurance: score(base_endurance, [[0,25], [26,50], [51,75], [76,100], [101,200], [201, 300]]),
      speed: score(speed, [[3,13], [14,17], [18,20], [21, 35]], 20),
      dexterity: score(dexterity, [[3,6], [7,10], [11,14], [15,17], [18,20], [21,35]], 5)
      # previous_rank: score(previous_rank, [[1,3], [4,6], [7,10], [11,15], [16,20], [21,30], [31,40], [41,50], [51,60], [61,100]], 0, true),
      # highest_rank: score(highest_rank, [[1,3], [4,6], [7,10], [11,15], [16,20], [21,30], [31,40], [41,50], [51,60], [61,100]],0, true),
      # endurance_round: score(endurance_round, [[1,2], [3,4], [5,6], [7,8], [9,10], [11,12], [13, 15]])
    }

    total_score = scores.values.sum
    normalized_score = [(total_score / scores.keys.size).round, 100].min
  end

  private
  def score(value, ranges, boost=0, is_rank=false)
    if is_rank
      # For rank attributes: Lower rank values get higher scores
      ranges.reverse_each.with_index do |range, index|
        if value.between?(range.first, range.last)
          # As we're iterating in reverse, (ranges.length - index) gives us the position from the start.
          # Multiply it by a factor (e.g., 20) to distribute scores across the range.
          return (ranges.length - index) * 20
        end
      end
    else
      ranges.each_with_index do |range, index|
        mid_score = (range.first + range.last) * 2
        mid_score += boost if value >= 18

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  before_action :set_fighter, only: %i[ show edit update destroy ]

  # GET /fighters or /fighters.json
  def index
    if params[:current_champs] == 'true'
      @fighters = Fighter.where(id: Title.where(lost_at: nil).select(:fighter_id)).order(:weight_class_id, :name)
    elsif params[:top_money] == 'true'
      @fighters = Fighter.all.sort_by { |fighter| -fighter.total_winnings }.take(10)
    elsif params[:unspent_level_points] == 'true'
      @fighters = Fighter.where('level_points > 0').order(level_points: :desc).limit(25)
    elsif params[:top_training_points] == 'true'
      @fighters = Fighter.where('training_points > 0').order(training_points: :desc).limit(25)
    elsif params[:needs_training] == 'true'
      @fighters = Fighter.needs_training
    else
      @fighters = Fighter.order(:weight_class_id, :name)
    end
  end

  # GET /fighters/1 or /fighters/1.json
  def show
  end

  # GET /fighters/new
  def new
    @fighter = Fighter.new
    @fighter.weight = (WeightClass.find(params[:weight_class_id]).max_weight - 2) if params[:weight_class_id].present?
    @weight_classes = WeightClass.all
  end

  # GET /fighters/1/edit
  def edit
    @weight_classes = WeightClass.all
  end

  # POST /fighters or /fighters.json
  def create
    @fighter = Fighter.new(fighter_params)

    respond_to do |format|
      if @fighter.save
        format.html { redirect_to fighter_url(@fighter), notice: "Fighter was successfully created." }
        format.json { render :show, status: :created, location: @fighter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fighters/1 or /fighters/1.json
  def update

    if params[:fighter][:buy_training_points] == "true"
      if @fighter.buy_training_points
        flash[:notice] = "Training points purchased!"
      else
        flash[:notice] = "Insufficient funds to purchase training points."
      end
      redirect_to @fighter and return
    end

    if params[:spend_points] == "true"
      if @fighter.level_points < 1
        flash[:notice] = "Insufficient level points to spend."
        redirect_to @fighter and return
      end
      @fighter.level_points -= 1
      @fighter.increase_endurance if params[:endurance]
    end

    respond_to do |format|
      if @fighter.update(fighter_params)
        format.html { redirect_to fighter_url(@fighter), notice: "Fighter was successfully updated." }
        format.json { render :show, status: :ok, location: @fighter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fighters/1 or /fighters/1.json
  def destroy
    @fighter.destroy

    respond_to do |format|
      format.html { redirect_to fighters_url, notice: "Fighter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_fighter
    @fighter = Fighter.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def fighter_params
    params.require(:fighter).permit(:name, :nickname, :birthplace, :punch, :strength, :speed, :dexterity, :base_endurance, :endurance, :endurance_round, :weight, :weight_class_id, :buy_training_points)
  end
end

app/helpers/fighters_helper.rb
module FightersHelper
  def score_color(score)
    case score
    when 0..45
      "text-red-500"
    when 46..50
      "text-orange-400"
    when 51..60
      "text-gray-500"
    when 61..70
      "text-purple-500"
    when 71..80
      "text-green-500 font-semibold"
    else
      "text-green-500 font-bold underline"
    end
  end
end

app/views/fighters/_fighter.html.erb
<div class="grid grid-cols-1 md:grid-cols-4 gap-6">
  <!-- Left Card -->

  <%= render partial: "fighter_card", locals: { fighter: fighter } %>


  <!-- Right Column -->

  <div class="col-span-1 md:col-span-3">
    <!-- Content for the right column -->
    <h2 class="text-xl font-bold text-gray-900">Level Up</h2>
    <% if fighter.level_points < 1 %>
      <p class="mb-1 mt-1">You have no level points.  Buying training points increase your chances to earn level points.</p>
    <% else %>
      <p class="mb-1 mt-1">You have <%= fighter.level_points %> level points.  Use points to level up.</p>
      <div class="flex items-center mb-1 mt-1"><%= button_to '+', { action: :update, controller: 'fighters', fighter: { punch: (fighter.punch + 1) }, spend_points: true }, method: :patch, class: "self-center rounded-md bg-indigo-600 mr-2 px-1.5 py-0.5 text-xs font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %><span class="mr-1 font-bold self-center">PCH:</span> <%= fighter.punch %></div>
      <div class="flex items-center mb-1 mt-1"><%= button_to '+', { action: :update, controller: 'fighters', fighter: { strength: (fighter.strength + 1) }, spend_points: true }, method: :patch, class: "self-center rounded-md bg-indigo-600 mr-2 px-1.5 py-0.5 text-xs font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %><span class="mr-1 font-bold self-center">STR:</span> <%= fighter.strength %></div>
      <div class="flex items-center mb-1 mt-1"><%= button_to '+', { action: :update, controller: 'fighters', fighter: { speed: (fighter.speed + 1) }, spend_points: true }, method: :patch, class: "self-center rounded-md bg-indigo-600 mr-2 px-1.5 py-0.5 text-xs font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %><span class="mr-1 font-bold self-center">SPD: </span> <%= fighter.speed %></div>
      <div class="flex items-center mb-1 mt-1"><%= button_to '+', { action: :update, controller: 'fighters', fighter: { dexterity: (fighter.dexterity + 1) }, spend_points: true }, method: :patch, class: "self-center rounded-md bg-indigo-600 mr-2 px-1.5 py-0.5 text-xs font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %><span class="mr-1 font-bold self-center">DEX: </span> <%= fighter.dexterity %></div>
      <div class="flex items-center mb-1 mt-1"><%= button_to '+', { action: :update, controller: 'fighters', fighter: { id: fighter.id }, endurance: true, spend_points: true }, method: :patch, class: "self-center rounded-md bg-indigo-600 mr-2 px-1.5 py-0.5 text-xs font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %><span class="mr-1 font-bold self-center">END: </span> <%= fighter.base_endurance %></div>
      <div class="flex items-center mb-1 mt-1"><%= button_to '+', { action: :update, controller: 'fighters', fighter: { endurance_round: (fighter.endurance_round + 1) }, spend_points: true }, method: :patch, class: "self-center rounded-md bg-indigo-600 mr-2 px-1.5 py-0.5 text-xs font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %><span class="mr-1 font-bold self-center">RND: </span> <%= fighter.endurance_round %></div>
    <% end %>
    <hr/>
    <p class="mb-1 mt-1">You have <%= fighter.training_points %> training points.  Buy training points to increase your chances to earn level points.</p>
    <p class="mb-1 mt-1">Training point cost <%= number_to_currency(fighter.training_point_cost(future: true), precision: 0) %>.</p>
    <% if fighter.balance > fighter.training_point_cost(future: true) %>
      <p class="mb-1 mt-1"><%= button_to 'Buy Training Point', { action: :update, controller: 'fighters', fighter: { buy_training_points: true } }, method: :patch, form_class: "d-inline", class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %></p>
    <% else %>
      <p class="mb-1 mt-1">You need <%= number_to_currency(fighter.training_point_cost(future: true) - fighter.balance, precision: 0) %> more to buy a training point.</p>
    <% end %>

    <h2 class="mt-5 text-xl font-bold text-gray-900">Past Titles</h2>
    <% if fighter.past_champion? %>
      <% fighter.titles.where.not(lost_at: nil).each do |title| %>
        <p class="mb-1 mt-1"><%= title.name %> (Lost <%= time_ago_in_words(title.lost_at) %> ago)</p>
      <% end %>
    <% else %>
      <p class="mb-1 mt-1">No</p>
    <% end %>

    <h2 class="mt-5 text-xl font-bold text-gray-900">Next Match</h2>

    <% if fighter.pending_matches.blank? %>
      <p class="mb-1 mt-1">No Matches Scheduled.</p>
      <% opponents = fighter.suggested_opponents %>
      <% if opponents.nil? %>
        <p class="font-bold">Suggested Opponents</p>
        <ul>
          <% fighter.suggested_opponents.each do |opponent| %>
            <li><%= link_to opponent.name, fighter_url(opponent), class: "text-blue-500 hover:underline" %> (Rank <%= opponent.rank %>) -> <%= link_to "Schedule Match", new_match_url(fighter_1_id: fighter.id, fighter_2_id: opponent.id, weight_class_id: fighter.weight_class.id), class: "text-blue-500 hover:underline" %></li>
          <% end %>
        </ul>
      <% else %>
        <p class="mb-1 mt-1"><%= link_to "Schedule one.", new_match_url(fighter_1_id: fighter.id, weight_class_id: fighter.weight_class.id), class: "text-blue-500 hover:underline" %></p>
      <% end %>
    <% else %>
      <% fighter.pending_matches.each do |match| %>
        <% opponent = match.opponent(fighter) %>

        <p class="mb-1 mt-1">
          vs
          <%= link_to opponent.name, fighter_url(opponent), class: "text-blue-500 hover:underline" %>
          (<%= opponent.wins %> - <%= opponent.losses %> - <%= opponent.draws %>
          ) <%= match.max_rounds %> Rounds
          [<%= link_to "Fight", fight_match_url(match), class: "text-blue-500 hover:underline" %>]
        </p>
      <% end %>
    <% end %>

    <h2 class="mt-5 text-xl font-bold text-gray-900">Match History</h2>

    <% fighter.completed_matches.each do |match| %>
      <p class="mb-1 mt-1">
        <%= match.created_at.strftime('%m/%d/%y') %>
        <% if match.fighter_1 != fighter %>
          <% opponent = match.fighter_1 %>
        <% else %>
          <% opponent = match.fighter_2 %>
        <% end %>
        <%= match.outcome(fighter) %>
        vs
        <%= link_to opponent.name, fighter_url(opponent), class: "text-blue-500 hover:underline" %>
        (<%= opponent.wins %> - <%= opponent.losses %> - <%= opponent.draws %>)
        <% if match.result_id == "ko" %>
          <%= match.rounds.count.ordinalize %> Round <%= match.result_id.upcase %>
        <% else %>
          <%= match.rounds.count.ordinalize %> Round Decision (<%= match.fighter_1_final_score %>
          to <%= match.fighter_2_final_score %>)
        <% end %>
        [<%= link_to "View", match_url(match), class: "text-blue-500 hover:underline" %>]
      </p>
    <% end %>

    <h2 class="mt-5 text-xl font-bold text-gray-900">Earnings / Ledger</h2>
    <p class="mb-1 mt-1 font-bold">Lifetime Earnings: <%= number_to_currency(fighter.total_winnings, precision: 0) %></p>
    <% fighter.ledgers.each do |ledger| %>
      <p class="mb-1 mt-1"><%= "#{ledger.transaction_date&.strftime('%m/%d/%y')} #{ledger.description}: #{number_to_currency(ledger.amount, precision: 0)}"  %></p>
    <% end %>



  </div>


</div>

app/views/fighters/edit.html.erb
<header class="bg-white shadow-sm">
  <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
    <h1 class="text-lg font-semibold leading-6 text-gray-900">Editing <%= @fighter.name %></h1>
    <%= link_to fighters_path, class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
      Back to Fighters
    <% end %>
  </div>
</header>


<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">

    <%= render "form", fighter: @fighter %>

  </div>
</main>

app/views/fighters/index.html.erb
<header class="bg-white shadow-sm">
  <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
    <h1 class="text-lg font-semibold leading-6 text-gray-900">Fighters</h1>
    <%= link_to new_fighter_path, class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
      New fighter
    <% end %>
  </div>
</header>


<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">

    <p style="color: green"><%= notice %></p>
    <p class="mb-5">
      <%= link_to "All", fighters_path, class: "text-blue-500 hover:underline" %> |
      <%= link_to "Current Champs", fighters_path(current_champs: true), class: "text-blue-500 hover:underline" %>  |
      <%= link_to "Top Money", fighters_path(top_money: true), class: "text-blue-500 hover:underline" %> |
      <%= link_to "Most Training Points", fighters_path(top_training_points: true), class: "text-blue-500 hover:underline" %> |
      <%= link_to "Unspent Level Points", fighters_path(unspent_level_points: true), class: "text-blue-500 hover:underline" %> |
      <%= link_to "Needs Training", fighters_path(needs_training: true), class: "text-blue-500 hover:underline" %>
    </p>

    <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">

      <% @fighters.each do |fighter| %>
        <%= render partial: "fighter_card", locals: { fighter: fighter } %>

    <% end %>

    </ul>

  </div>
</main>

app/views/fighters/new.html.erb
<header class="bg-white shadow-sm">
  <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
    <h1 class="text-lg font-semibold leading-6 text-gray-900">Create New Fighter</h1>
    <%= link_to fighters_path, class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
      Back to Fighters
    <% end %>
  </div>
</header>


<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">

    <%= render "form", locals: { fighter: @fighter, weight_classes: @weight_classes } %>

  </div>
</main>