config/routes.rb
Rails.application.routes.draw do
  resources :weight_classes
  resources :fighters
  resources :matches do
    member do
      get 'fight'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "fighters#index"
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :fighter_1, class_name: 'Fighter'
  belongs_to :fighter_2, class_name: 'Fighter'
  belongs_to :winner, class_name: 'Fighter', optional: true # Winner is optional because a match might not be finished yet
  belongs_to :weight_class, :optional => true
  has_many :rounds

  enum status_id: { pending: 0, completed: 1 }
  enum result_id: { decision: 0, tko: 1, ko: 2 }

  before_save :set_default_status, if: :new_record?

  before_save :set_weight_class
  before_save :set_default_rounds
  before_save :set_match_purse
  before_save :set_split_purses

  def set_split_purses
    return if self.fighter_1_split.present? && self.fighter_2_split.present? # Exit if split purses are already set

    # Determine the fighters' ranks (you may need to adjust how you retrieve ranks)
    fighter_1_rank = fighter_1.rank
    fighter_2_rank = fighter_2.rank

    Rails.logger.info "set_split_purse: Fighter 1 Rank: #{fighter_1_rank}"
    Rails.logger.info "set_split_purse: Fighter 2 Rank: #{fighter_2_rank}"

    # Check if both fighters have no rank (default to 50/50 split)
    if fighter_1_rank.nil? && fighter_2_rank.nil?
      puts "Both fighters have no rank 50/50 split"
      self.fighter_1_split ||= 0.5
      self.fighter_2_split ||= 0.5
    else


      # Determine the split based on ranks and random percentages
      if fighter_1_rank.nil?
        self.fighter_1_split ||= 0.1
        self.fighter_2_split ||= 0.9
      elsif fighter_2_rank.nil?
        self.fighter_2_split ||= 0.1
        self.fighter_1_split ||= 0.9
      else
        # Both fighters have ranks
        # Calculate the rank difference
        rank_difference = (fighter_1_rank - fighter_2_rank).abs

        # Calculate the base split percentage (50%)
        base_split = 0.5

        # Calculate the split factor based on rank difference
        split_factor = (rank_difference + 1) * 0.065  # Adjust this factor as needed

        # Ensure the split factor is within the range [0, 0.5]
        split_factor = [split_factor, 0.45].min
        split_factor = [split_factor, 0.0].max

        # Assign splits based on fighter ranks
        if fighter_1_rank < fighter_2_rank
          self.fighter_1_split ||= base_split + split_factor
          self.fighter_2_split ||= base_split - split_factor
        else
          self.fighter_2_split ||= base_split + split_factor
          self.fighter_1_split ||= base_split - split_factor
        end
      end
    end
  end
  def set_match_purse
    return if self.match_purse.present? # Exit if match_purse is already set

    self.match_purse =
      case highest_rank
      when 1..3
        if fighter_1.past_champion? || fighter_2.past_champion? || fighter_1.current_champion? || fighter_2.current_champion?
          (rand(1..20) + 10) * 1000
        elsif fighter_1.current_champion? && fighter_2.current_champion?
          (rand(1..20) + 12) * 1000
        else
          rand(1..20) * 1000
        end
      when 4..6
        rand(1..12) * 1000
      when 7..9
        rand(1..10) * 1000
      else
        rand(1..8) * 1000
      end
    modifer =
      case most_matches
      when 10..15
        4
      when 16..20
        5
      when 21..25
        6
      when 26..30
        7
      when 31..35
        8
      when 36..40
        9
      when 41..45
        10
      else
        2
      end
    self.match_purse *= modifer
  end
  def set_weight_class
    higher_weight = [fighter_1.weight, fighter_2.weight].max
    self.weight_class = WeightClass.find_highest_class_for_weight(higher_weight)
  end

  def set_default_status
    self.status_id ||= 0
  end

  def self.roll_d20
    rand(1..20)
  end

  def fighter_recovery(round)
    fighter_1.round_recovery(round)
    fighter_2.round_recovery(round)
  end
  def punch_roll(offensive_fighter, offensive_penalty)
    roll = Match.roll_d20
    adjusted_punch = offensive_fighter.punch + offensive_penalty
    case adjusted_punch
    when 3..6
      roll -= 2
    when 7..10
      roll -= 1
    when 11..14
      roll -= 0
    when 15..17
      roll += 1
    when 18..20
      roll += 2
    when 21..35
      roll += 3
    when 36..45
      roll += 4
    else
      roll -= 2
    end
    roll = 1 if roll < 1
    roll
  end

  def adjust_dexterity(defensive_fighter, defensive_penalty)
    modified_dexterity = defensive_fighter.dexterity + defensive_penalty
    case defensive_fighter.dexterity
    when 1..6
      modified_dexterity -= 2
    when 7..10
      modified_dexterity -= 1
    when 11..14
      modified_dexterity -= 0
    when 15..17
      modified_dexterity += 1
    when 18..20
      modified_dexterity += 2
    when 21..35
      modified_dexterity += 3
    when 36..45
      modified_dexterity += 4
    else
      0
    end
    modified_dexterity
  end

  def set_endurance_penalty(fighter, round)
    penalty = fighter.endurance_round - round
    if penalty < 0
      penalty
    else
      0
    end
  end

  def punch(offensive_fighter, defensive_fighter, round, fighter_number)

    return "#{offensive_fighter.name} lays on mat lifeless." if winner_id.present?
    offensive_penalty = set_endurance_penalty(offensive_fighter, round.round_number)
    defensive_penalty = set_endurance_penalty(defensive_fighter, round.round_number)

    roll = punch_roll(offensive_fighter, offensive_penalty)

    damage = calculate_damage(offensive_fighter, defensive_fighter, offensive_penalty, defensive_penalty)

    debug = true
    debug = "#{offensive_fighter.name} rolled a #{roll}. Punch: #{offensive_fighter.punch} Penalty: #{offensive_penalty}"
    case roll
    when 1..5
      score_round(round, fighter_number, 0)
      "missed. #{debug if debug}"
    when 6..10
      score_round(round, fighter_number, damage)
      reduce_health(defensive_fighter, damage)
      if defensive_fighter.endurance <= 0
        end_match(offensive_fighter, defensive_fighter, damage)
      else
        "landed a body blow. #{defensive_fighter.name} takes #{damage} damage. #{debug if debug}"
      end
    when 11..15
      score_round(round, fighter_number, damage)
      reduce_health(defensive_fighter, damage)
      if defensive_fighter.endurance <= 0
        end_match(offensive_fighter, defensive_fighter, damage)
      else
        "stuck a jab. #{defensive_fighter.name} takes #{damage} damage. #{debug if debug}"
      end
    when 16..18
      score_round(round, fighter_number, damage)
      reduce_health(defensive_fighter, damage)
      if defensive_fighter.endurance <= 0
        end_match(offensive_fighter, defensive_fighter, damage)
      else
        "solid head shot. #{defensive_fighter.name} takes #{damage} damage. #{debug if debug}"
      end
    when 19..30
      reduce_health(defensive_fighter, damage)

      # Check for Technical Knockout
      if fighter_number == 1
        round.fighter_1_knockdowns = 1
        if rounds.sum(:fighter_1_knockdowns) >= 2
          score_round(round, fighter_number, damage)
          end_match(offensive_fighter, defensive_fighter, damage, false)
          return
        end
      elsif fighter_number == 2
        round.fighter_2_knockdowns = 1
        if rounds.sum(:fighter_2_knockdowns) >= 2
          score_round(round, fighter_number, damage)
          end_match(offensive_fighter, defensive_fighter, damage, false)
          return
        end
      end

      # Check for Knockout
      knockout = determine_knockout(defensive_fighter, damage, defensive_penalty)
      score_round(round, fighter_number, damage)
      if knockout
        end_match(offensive_fighter, defensive_fighter, damage)
      else
        "KNOCKED #{defensive_fighter.name} DOWN. #{defensive_fighter.name} takes #{damage} damage. #{debug if debug}"
      end
    else
      "WTF? #{debug if debug}. This should never happen."
    end
  end

  def end_match(offensive_fighter, defensive_fighter, damage, knockout = true)
    self.winner = offensive_fighter
    if knockout
      self.ko!
      "HAS KNOCKED OUT #{defensive_fighter.name} inflicting #{damage} damage."
    else
      self.tko!
      "HAS TECHNICALLY KNOCKED OUT #{defensive_fighter.name} inflicting #{damage} damage."
    end
  end

  def score_round(round, fighter_number, damage)
    if fighter_number == 1
      round.fighter_1_points = damage
      round.fighter_1_points += 10 if round.fighter_1_knockdowns > 0
    end
    if fighter_number == 2
      round.fighter_2_points = damage
      round.fighter_2_points += 10 if round.fighter_2_knockdowns > 0
    end
    round.save
  end

  def reduce_health(defensive_fighter, damage)
    defensive_fighter.endurance -= damage
    defensive_fighter.endurance = 0 if defensive_fighter.endurance < 0
    defensive_fighter.save!
  end

  def calculate_damage(offensive_fighter, defensive_fighter, offensive_penalty, defensive_penalty)
    damage = punch_strength(offensive_fighter, offensive_penalty)
    damage_modifier = dexterity_modifier(defensive_fighter, defensive_penalty)
    (damage * damage_modifier).round
  end

  def determine_knockout(defensive_fighter, damage, defensive_penalty)
    case defensive_fighter.speed + defensive_penalty
    when 3..13
      true
    when 14..17
      if rand(1..100) > 50
        false
      else
        true
      end
    when 18..30
      if ((damage > 10) && (rand(1..100) < 40)) || ((defensive_fighter.endurance < 20) && (rand(1..100) < 50 ))
        true
      else
        false
      end
    else
      false
    end
  end

  def dexterity_modifier(defensive_fighter, defensive_penalty)
    modified_dexterity = adjust_dexterity(defensive_fighter, defensive_penalty)

    case modified_dexterity
    when 1..9
      1
    when 10..14
      0.5
    when 15..18
      0.75
    when 15..17
      2
    when 19..20
      0
    else
      0
    end
  end

  def punch_strength(offensive_fighter,offensive_penalty)
    strength = offensive_fighter.strength + offensive_penalty
    case strength
    when 3..6
      rand(1..4)
    when 7..10
      rand(1..6)

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    if params[:status] == "completed"
      @matches = Match.where(status_id: :completed).order(:match_purse)
    else
      @matches = Match.where(status_id: :pending).order(:match_purse)
    end
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
    @match.fighter_1 = Fighter.find(params[:fighter_1_id]) if params[:fighter_1_id].present?
    @match.fighter_2 = Fighter.find(params[:fighter_2_id]) if params[:fighter_2_id].present?
    if params[:weight_class_id].present?
      @fighters = Fighter.where(weight_class_id: params[:weight_class_id]).order(:name)
    else
      @fighters = Fighter.all.order(:name)
    end
    @weight_classes = WeightClass.all
  end

  # GET /matches/1/fight
  def fight
    @match = Match.find(params[:id])
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
    @fighters = Fighter.all.order(:name)
    @weight_classes = WeightClass.all
  end

  # POST /matches or /matches.json
  def create
    params[:match][:status_id] = params[:match][:status_id].to_i if params[:match][:status_id].present?
    puts params[:match][:status_id]
    @match = Match.new(match_params)
    @weight_classes = WeightClass.all
    @fighters = Fighter.all

    respond_to do |format|
      if @match.save
        format.html { redirect_to matches_url, notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    params[:match][:status_id] = params[:match][:status_id].to_i if params[:match][:status_id].present?
    puts params[:match][:status_id]

    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to matches_url, notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:max_rounds, :fighter_1_id, :fighter_2_id, :status_id, :winner_id, :result_id, :weight_class_id)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/edit.html.erb
<header class="bg-white shadow-sm">
<div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
    <h1 class="text-lg font-semibold leading-6 text-gray-900">Editing Match: <%= @match.id %></h1>
    <%= link_to matches_path, class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
      Back to Matches
    <% end %>
  </div>
</header>


<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">

    <%= render "form", match: @match %>

  </div>
</main>

app/views/matches/fight.html.erb
<header class="bg-white shadow-sm">
  <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
    <h1 class="text-lg font-semibold leading-6 text-gray-900">Fight <%= "#{@match.fighter_1.name} vs #{@match.fighter_2.name}" %></h1>
    <%= link_to matches_path, class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
      Back to Matches
    <% end %>
  </div>
</header>


<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
    <% @match.training %>
    <% rounds = @match.max_rounds || 4 %>
    <% (1..rounds).each do |round| %>
      <% if @match.winner_id.nil? %>
        <% new_round = @match.rounds.build(round_number: round) %>
        <h2 class="text-lg font-medium leading-5 text-gray-800 py-2">Round <%= round %></h2>

        <div class="flex items-center py-2">
          <%= image_tag("sample_boxer.gif", class: "w-10 h-10 rounded-full", alt: @match.fighter_1.name) %>
          <span class="ml-4 text-gray-700">
          <%= "#{@match.fighter_1.name} #{@match.punch(@match.fighter_1, @match.fighter_2, new_round, 1)}" %>
        </span>
        </div>

        <div class="flex items-center py-2">
          <%= image_tag("sample_boxer.gif", class: "w-10 h-10 rounded-full", alt: @match.fighter_2.name) %>
          <span class="ml-4 text-gray-700">
          <%= "#{@match.fighter_2.name} #{@match.punch(@match.fighter_2, @match.fighter_1, new_round, 2)}" %>
        </span>
        </div>
        <div class="mb-5">
          Round Score: <%= "#{@match.fighter_1.name} : #{new_round.fighter_1_points} - #{@match.fighter_2.name} : #{new_round.fighter_2_points}" %>
        </div>
        <% @match.fighter_recovery(round) %>
        <div class="mb-5">
          Round Recovery: <%= "#{@match.fighter_1.name} : #{@match.fighter_1.endurance}/#{@match.fighter_1.base_endurance} - #{@match.fighter_2.name} : #{@match.fighter_2.endurance}/#{@match.fighter_2.base_endurance}" %>
        </div>

  <% end %>
    <% end %>
    <% @match.score_match %>
    <% @match.training %>

    <h2 class="text-lg font-medium leading-5 text-gray-800 py-2">Match Score</h2>
    <% if @match.winner_id.nil? %>
      <div>Match is a draw!</div>
    <% else %>
      <div>
        <%= link_to @match.winner&.name, fighter_path(@match.winner), class: "text-blue-500 hover:underline" %> winner
        by <%= @match.result_id.upcase %> in the <%= @match.rounds.count.ordinalize %> round!
      </div>
    <% end %>
    <% if @match.result_id == 'decision' %>
      <div>
        <%= link_to(@match.fighter_1.name, fighter_path(@match.fighter_1), class: "text-blue-500 hover:underline") %> <%= @match.fighter_1_final_score %>
        - <%= link_to @match.fighter_2.name, fighter_path(@match.fighter_2), class: "text-blue-500 hover:underline" %> <%= @match.fighter_2_final_score %>
      </div>
    <% end %>
    <div class="mt-5"><%= link_to("View #{@match.weight_class.name} rankings.", weight_class_path(@match.weight_class), class: "text-blue-500 hover:underline") %></div>
  </div>
</main>

app/views/matches/index.html.erb
<header class="bg-white shadow-sm">
  <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
    <h1 class="text-lg font-semibold leading-6 text-gray-900">Matches</h1>
    <%= link_to new_match_path, class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
      New Match
    <% end %>
  </div>
</header>


<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
    <p class="mb-4"><%= link_to("Past Matches", matches_url(status: "completed"), class: "text-blue-500 hover:underline") %> | <%= link_to("Pending Matches", matches_url(), class: "text-blue-500 hover:underline") %></p>
    <p style="color: green"><%= notice %></p>

    <% if @matches.count < 1 %>
      <p class="mb-1 mt-1">No Matches Scheduled.  <%= link_to "Schedule one now.", new_match_url(), class: "text-blue-500 hover:underline" %></p>
    <% else %>

    <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">

      <% @matches.each do |match| %>
        <li class="col-span-1 flex flex-col divide-y divide-gray-200 rounded-lg bg-white text-center shadow">
          <div class="flex flex-1 flex-col p-8">
            <h2 class="mt-6 text-sm font-bold text-gray-900"><%= "#{match.fighter_1.name} (#{match.fighter_1&.rank})" %></h2>
            <h3 class="mt-1 text-sm text-gray-900"><%= "Rating: #{match.fighter_1&.power_score}" %></h3>
            <p>vs</p>
            <h2 class="mt-1 text-sm font-bold text-gray-900"><%= "#{match.fighter_2.name} (#{match.fighter_2&.rank})" %></h2>
            <h3 class="mt-1 text-sm text-gray-900"><%= "Rating: #{match.fighter_2&.power_score}" %></h3>
            <h3 class="mt-1 text-sm text-gray-900"><%= number_to_currency(match.match_purse, precision: 0) %></h3>
            <% unless match.fighter_1_split.nil? || match.fighter_2_split.nil? %>
              <h3 class="mt-1 text-sm text-gray-900"><%= "#{(match.fighter_1_split * 100).round}% : #{(match.fighter_2_split * 100).round}%" %></h3>
            <% end %>
            <h3 class="mt-1 text-sm text-gray-900"><%= "Rounds: #{match.max_rounds}" %></h3>

            <%= link_to weight_class_path(match.weight_class) do %>
              <dd class="mt-3">
            <span class="inline-flex items-center rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
              <%= match.weight_class&.name %>
            </span>
              </dd>


            <% end %>
            <% if match.pending? %>
              <div class="flex divide-x divide-gray-200">
                <div class="flex w-0 flex-1">
                  <%= link_to edit_match_path(match), class: "relative inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-bl-lg border border-transparent py-4 text-sm font-semibold text-gray-900" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                      <path d="M21.731 2.269a2.625 2.625 0 00-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 000-3.712zM19.513 8.199l-3.712-3.712-12.15 12.15a5.25 5.25 0 00-1.32 2.214l-.8 2.685a.75.75 0 00.933.933l2.685-.8a5.25 5.25 0 002.214-1.32L19.513 8.2z"/>
                    </svg>
                    Edit
                  <% end %>
                </div>
                <div class="flex w-0 flex-1">
                  <%= link_to fight_match_path(match), class: "relative inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-bl-lg border border-transparent py-4 text-sm font-semibold text-gray-900" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0M3.124 7.5A8.969 8.969 0 015.292 3m13.416 0a8.969 8.969 0 012.168 4.5"/>
                    </svg>
                    Fight
                  <% end %>
                </div>
              </div>
            <% else %>
              <div class="font-bold">Winner</div> <%= match.winner&.name %>
            <% end %>
            <div>
              <%= link_to match, class: "relative inline-flex flex-1 items-center justify-center gap-x-3 rounded-bl-lg border border-transparent py-4 text-sm font-semibold text-gray-900" do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184" />
                </svg>
                Fight Card
              <% end %>
            </div>

          </div>
        </li>

      <% end %>

    </ul>
    <% end %>
  </div>
</main>

app/views/matches/new.html.erb
<header class="bg-white shadow-sm">
  <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
    <h1 class="text-lg font-semibold leading-6 text-gray-900">Create New Match</h1>
    <%= link_to matches_path, class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
      Back to Matches
    <% end %>
  </div>
</header>


<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">

    <%= render "form", match: @match %>

  </div>
</main>

app/views/matches/show.html.erb
<header class="bg-white shadow-sm">
  <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
    <h1 class="text-lg font-semibold leading-6 text-gray-900">
      <%= @match.fighter_1.name %> vs <%= @match.fighter_2.name %>
      <span class="text-sm text-gray-400 italic">(<%= @match.max_rounds %>)</span>
    </h1>
    <%= link_to edit_match_path(@match), class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
      Edit Match
    <% end %>
  </div>
</header>

<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">

    <p style="color: green"><%= notice %></p>


    <div class="flex mt-10">
      <div class="w-2/5 mx-auto">
        <!-- Content for the first column (45%) -->
        <%= render partial: "fighters/fighter_card", locals: { fighter: @match.fighter_1 } %>
      </div>
      <div class="w-1/5 mx-auto flex flex-col items-center justify-center">
        <!-- Content for the second column (10%) -->
        <div class="text-center text-3xl font-bold">VS</div>
        <div class="mt-3 text-center"><%= @match.max_rounds %> Rounds</div>
        <div class="mt-3 text-center font-bold">Purse</div>
        <div><%= number_to_currency(@match.match_purse, precision: 0) %></div>
        <div class="mt-5">
          <%= link_to fight_match_path(@match), class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
            Fight
          <% end %>
        </div>
      </div>
      <div class="w-2/5 mx-auto">
        <!-- Content for the third column (45%) -->
        <%= render partial: "fighters/fighter_card", locals: { fighter: @match.fighter_2 } %>
      </div>
    </div>

    <div class="mt-10 flex items-center justify-end gap-x-6">
      <%= link_to matches_url, class: "text-sm font-semibold leading-6 text-gray-900" do %>
        Back to Matches
      <% end %>
      <%= button_to "Delete", @match, method: :delete, class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>

    </div>


  </div>
</main>