config/routes.rb
Rails.application.routes.draw do
  resources :weight_classes
  resources :fighters
  resources :matches do
    member do
      get 'fight'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "fighters#index"
end

app/controllers/weight_classes_controller.rb
class WeightClassesController < ApplicationController
  before_action :set_weight_class, only: %i[ show edit update destroy ]

  # GET /weight_classes or /weight_classes.json
  def index
    @weight_classes = WeightClass.all
  end

  # GET /weight_classes/1 or /weight_classes/1.json
  def show
  end

  # GET /weight_classes/new
  def new
    @weight_class = WeightClass.new
  end

  # GET /weight_classes/1/edit
  def edit
  end

  # POST /weight_classes or /weight_classes.json
  def create
    @weight_class = WeightClass.new(weight_class_params)

    respond_to do |format|
      if @weight_class.save
        format.html { redirect_to weight_classes_url, notice: "Weight class was successfully created." }
        format.json { render :show, status: :created, location: @weight_class }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weight_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weight_classes/1 or /weight_classes/1.json
  def update
    respond_to do |format|
      if @weight_class.update(weight_class_params)
        format.html { redirect_to weight_classes_url, notice: "Weight class was successfully updated." }
        format.json { render :show, status: :ok, location: @weight_class }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weight_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weight_classes/1 or /weight_classes/1.json
  def destroy
    @weight_class.destroy

    respond_to do |format|
      format.html { redirect_to weight_classes_url, notice: "Weight class was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight_class
      @weight_class = WeightClass.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def weight_class_params
      params.require(:weight_class).permit(:name, :max_weight)
    end
end

app/helpers/weight_classes_helper.rb
module WeightClassesHelper
end

app/views/weight_classes/_form.html.erb
<%= form_with(model: weight_class) do |form| %>
  <% if weight_class.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(weight_class.errors.count, "error") %> prohibited this weight_class from being saved:</h2>

      <ul>
        <% weight_class.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-span-full">
    <%= form.label :name, class: "block text-sm font-medium leading-6 text-gray-900" %>
    <%= form.text_field :name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
  </div>

  <div class="col-span-full">
    <%= form.label :max_weight, class: "block text-sm font-medium leading-6 text-gray-900" %>
    <%= form.number_field :max_weight, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
  </div>

  <div class="mt-6 flex items-center justify-end gap-x-6">
    <%= link_to weight_classes_url, class: "text-sm font-semibold leading-6 text-gray-900" do %>
      Cancel
    <% end %>
    <%= form.submit class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
  </div>
<% end %>

app/views/weight_classes/_weight_class.html.erb
<div id="<%= dom_id weight_class %>">
  <p>
    <strong>Name:</strong>
    <%= weight_class.name %>
  </p>

  <p>
    <strong>Max weight:</strong>
    <%= weight_class.max_weight %>
  </p>
</div>

app/views/weight_classes/edit.html.erb
<header class="bg-white shadow-sm">
  <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
    <h1 class="text-lg font-semibold leading-6 text-gray-900">Editing Match: <%= @weight_class.name %></h1>
    <%= link_to weight_classes_path, class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
      Back to Weight Classes
    <% end %>
  </div>
</header>


<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">

    <%= render "form", weight_class: @weight_class %>

  </div>
</main>

app/views/weight_classes/index.html.erb
<header class="bg-white shadow-sm">
  <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
    <h1 class="text-lg font-semibold leading-6 text-gray-900">Weight Classes</h1>
    <%= link_to new_weight_class_path, class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
      New Weight Class
    <% end %>
  </div>
</header>


<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">

    <p style="color: green"><%= notice %></p>

    <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">

      <% @weight_classes.each do |weight_class| %>
        <li class="col-span-1 flex flex-col divide-y divide-gray-200 rounded-lg bg-white text-center shadow">
          <div class="flex flex-1 flex-col p-8">

            <h2 class="mt-1 text-xl font-bold text-gray-900"><%= weight_class.name %></h2>
            <p class="mt-2 text-lg font-semibold text-gray-900"><%= weight_class.fighters.count %> Fighters</p>
            <h3 class="mt-1 text-sm text-gray-800">Max Weight (<%= weight_class.max_weight %>lbs)</h3>
            <p class="mt-1 text-sm text-gray-800"><%= weight_class.matches.count %> Matches</p>

            <div class="-mt-px flex divide-x divide-gray-200">
              <div class="flex w-0 flex-1">
                <%= link_to edit_weight_class_path(weight_class), class: "relative -mr-px inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-bl-lg border border-transparent py-4 text-sm font-semibold text-gray-900" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                    <path d="M21.731 2.269a2.625 2.625 0 00-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 000-3.712zM19.513 8.199l-3.712-3.712-12.15 12.15a5.25 5.25 0 00-1.32 2.214l-.8 2.685a.75.75 0 00.933.933l2.685-.8a5.25 5.25 0 002.214-1.32L19.513 8.2z" />
                  </svg>
                  Edit
                <% end %>
              </div>
              <div class="flex w-0 flex-1">
                <%= link_to weight_class_path(weight_class), class: "relative inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-bl-lg border border-transparent py-4 text-sm font-semibold text-gray-900" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z" />
                  </svg>
                  Show
                <% end %>
              </div>
            </div>
          </div>
        </li>

      <% end %>

    </ul>

  </div>
</main>

app/views/weight_classes/new.html.erb
<header class="bg-white shadow-sm">
  <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
    <h1 class="text-lg font-semibold leading-6 text-gray-900">Create Weight Class</h1>
    <%= link_to weight_classes_path, class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
      Back to Weight Classes
    <% end %>
  </div>
</header>


<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">

    <%= render "form", weight_class: @weight_class %>

  </div>
</main>

app/views/weight_classes/show.html.erb
<header class="bg-white shadow-sm">
  <div class="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8 flex items-center justify-between">
    <h1 class="text-lg font-semibold leading-6 text-gray-900">
      <%= @weight_class.name %>
      <span class="text-sm text-gray-400 italic">(Max Weight: <%= @weight_class.max_weight %> lbs)</span>
    </h1>
    <%= link_to edit_weight_class_path(@weight_class), class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
      Edit Weight Class
    <% end %>
  </div>
</header>


<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">

    <p style="color: green"><%= notice %></p>

    <div class="px-4 sm:px-6 lg:px-8">
      <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
          <h1 class="mt-6 text-base font-semibold leading-6 text-gray-900">Rankings</h1>
        </div>
      </div>
      <div class="mt-2 flow-root">
        <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
            <table class="min-w-full divide-y divide-gray-300">
              <thead>
              <tr>
                <th scope="col" class="px-1 py-3.5 text-center text-sm font-semibold text-gray-900">Curr Rank</th>
                <th scope="col" class="px-1 py-3.5 text-center text-sm font-semibold text-gray-900">Prev Rank</th>
                <th scope="col" class="px-1 py-3.5 text-center text-sm font-semibold text-gray-900">High Rank</th>
                <th scope="col" class="px-1 py-3.5 text-center text-sm font-semibold text-gray-900">Power Score</th>
                <th scope="col" class="px-1 py-3.5 text-center text-sm font-semibold text-gray-900">Streak</th>
                <th scope="col" class="px-1 py-3.5 text-center text-sm font-semibold text-gray-900">Lifetime Earnings</th>
                <th scope="col" class="px-1 py-3.5 text-center text-sm font-semibold text-gray-900">Current Balance</th>
                <th scope="col" class="px-1 py-3.5 text-left text-sm font-semibold text-gray-900">Current Title(s)</th>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Fighter</th>
                <th scope="col" class="px-1 py-3.5 text-center text-sm font-semibold text-gray-900">Record</th>
                <th scope="col" class="px-1 py-3.5 text-center text-sm font-semibold text-gray-900">Win Pct</th>
                <th scope="col" class="px-1 py-3.5 text-center text-sm font-semibold text-gray-900">TM</th>
                <th scope="col" class="px-1 py-3.5 text-center text-sm font-semibold text-gray-900">Lvl Pts</th>
                <th scope="col" class="px-1 py-3.5 text-center text-sm font-semibold text-gray-900">Trn Pts</th>
                <th scope="col" class="px-1 py-3.5 text-left text-sm font-semibold text-gray-900">Last Opponent</th>
                <th scope="col" class="px-1 py-3.5 text-left text-sm font-semibold text-gray-900">Next Match</th>
              </tr>
              </thead>
              <tbody class="divide-y divide-gray-200">

              <% @weight_class.fighters.sort_by { |fighter| fighter.rank }.each do |fighter| %>
              <% next_opponent =  fighter.pending_matches.first&.opponent(fighter) %>
              <% last_opponent =  fighter.completed_matches.last&.opponent(fighter) %>

              <tr>
                <td class="whitespace-nowrap px-1 py-2 text-center text-sm text-gray-500"><%= fighter.rank %></td>
                <td class="whitespace-nowrap px-1 py-2 text-center text-sm text-gray-500"><%= fighter.previous_rank %></td>
                <td class="whitespace-nowrap px-1 py-2 text-center text-sm text-gray-500"><%= fighter.highest_rank %></td>
                <td class="whitespace-nowrap px-1 py-2 text-center text-sm <%= score_color(fighter.power_score) %>"><%= fighter.power_score %></td>
                <td class="whitespace-nowrap px-1 py-2 text-center text-sm text-gray-500"><%= fighter.win_or_loss_streak %></td>
                <td class="whitespace-nowrap px-1 py-2 text-right text-sm text-gray-500"><%= number_to_currency(fighter.total_winnings, precision: 0) %></td>
                <td class="whitespace-nowrap px-1 py-2 text-right text-sm text-gray-500"><%= number_to_currency(fighter.balance, precision: 0) %></td>
                <% if fighter.current_champion? %>
                  <td class="whitespace-nowrap px-1 py-2 text-left text-sm text-gray-500 relative group">
                      <%= fighter.abbreviated_curent_titles_list %>
                  </td>
                <% else %>
                  <td>&nbsp;</td>
                <% end %>

                <td class="whitespace-nowrap py-2 pl-4 pr-3 text-left text-sm font-medium text-gray-900 sm:pl-0"><%= link_to fighter.name, fighter_url(fighter), class: "text-blue-500 hover:underline" %></td>
                <td class="whitespace-nowrap px-1 py-2 text-center text-sm text-gray-500"><%= fighter.wins %> - <%= fighter.losses %> - <%= fighter.draws %> (<%= fighter.knockouts %> KOs)</td>
                <td class="whitespace-nowrap px-1 py-2 text-center text-sm text-gray-500"><%= number_with_precision(fighter.winning_percentage, precision: 3).sub(/^0/, '') %></td>
                <td class="whitespace-nowrap py-2 pl-4 text-center text-sm text-gray-500"><%= fighter.total_matches %></td>
                <td class="whitespace-nowrap px-1 py-2 text-center text-sm text-gray-500"><%= fighter.level_points %></td>
                <td class="whitespace-nowrap px-1 py-2 text-center text-sm text-gray-500"><%= fighter.training_points %></td>
                <% if last_opponent.nil? %>
                  <td class="whitespace-nowrap px-1 py-2 text-left text-sm text-gray-500">No Fights</td>
                <% else %>
                  <td class="whitespace-nowrap px-1 py-2 text-left text-sm text-gray-500"><%= link_to last_opponent&.name, fighter_url(last_opponent), class: "text-blue-500 hover:underline" %></td>
                <% end %>
                <% if next_opponent.nil? %>
                  <% suggested_opponent = fighter.suggested_opponents.first %>
                  <% if suggested_opponent %>
                    <td class="whitespace-nowrap px-1 py-2 text-left text-sm text-gray-500"><%= link_to "Schedule #{suggested_opponent.name}", new_match_url(fighter_1_id: fighter.id, fighter_2_id: suggested_opponent.id, weight_class_id: @weight_class.id), class: "text-blue-500 hover:underline" %></td>
                  <% else %>
                    <td class="whitespace-nowrap px-1 py-2 text-left text-sm text-gray-500"><%= link_to "Schedule One", new_match_url(fighter_1_id: fighter.id, weight_class_id: @weight_class.id), class: "text-blue-500 hover:underline" %></td>
                  <% end %>
                <% else %>
                  <td class="whitespace-nowrap px-1 py-2 text-left text-sm text-gray-500"><%= link_to next_opponent&.name, fighter_url(next_opponent), class: "text-blue-500 hover:underline" %></td>
                <% end %>
              </tr>
              <% end %>

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>



    <div class="mt-10 flex items-center justify-end gap-x-6">
      <%= link_to new_fighter_url(weight_class_id: @weight_class.id), class: "text-sm font-semibold leading-6 text-gray-900" do %>
        Create Fighter in <%= @weight_class.name %>
      <% end %>
      <%= link_to weight_classes_url, class: "text-sm font-semibold leading-6 text-gray-900" do %>
        Back to Weight Classes
      <% end %>
      <%= button_to "Delete", @weight_class, method: :delete, class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>

    </div>


  </div>
</main>